name: test-js
on: [push]
defaults:
  run:
    working-directory: ./js

jobs:
  test-js:
    name: test-js
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun test --coverage
